/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Rafael Rodrigues (https://sketchfab.com/RafaelBR873D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-computers-7bb6e720499a467b8e0427451d180063
Title: Old Computers
*/

import { useGLTF } from '@react-three/drei'

const OldComputers = (props) => {
    const { nodes, materials } = useGLTF('/models/old_computers.glb')
    return (
        <group {...props} dispose={null}>
            <group position={[0.26999998, 1.52948081, -2.61336708]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_206.geometry}
                    material={materials.Texture}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_207.geometry}
                    material={materials.Screen}
                />
            </group>
            <group position={[-1.42970824, 2.49567342, -1.80016661]} rotation={[0, 1.00192952, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_209.geometry}
                    material={materials.Texture}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_210.geometry}
                    material={materials.Screen}
                />
            </group>
            <group position={[-2.73113871, 0.6294809, -0.52235556]} rotation={[0, 1.08704725, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_212.geometry}
                    material={materials.Texture}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_213.geometry}
                    material={materials.Screen}
                />
            </group>
            <group position={[1.8449049, 0.37702101, -1.77068293]} rotation={[0, -Math.PI / 9, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_215.geometry}
                    material={materials.Texture}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_216.geometry}
                    material={materials.Screen}
                />
            </group>
            <group
                position={[3.11016536, 2.14521098, -0.18009996]}
                rotation={[0, -0.7925426, 0]}
                scale={0.81000006}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_218.geometry}
                    material={materials.Texture}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_219.geometry}
                    material={materials.Screen}
                />
            </group>
            <group
                position={[-3.41726995, 3.05608177, 1.3026042]}
                rotation={[0, 1.22173048, 0]}
                scale={0.90000004}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_221.geometry}
                    material={materials.Texture}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_222.geometry}
                    material={materials.Screen}
                />
            </group>
            <group position={[-3.89907193, 4.28699207, -2.64211988]} rotation={[0, 0.53879834, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_224.geometry}
                    material={materials.Texture}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_225.geometry}
                    material={materials.Screen}
                />
            </group>
            <group
                position={[0.99231702, 4.28699207, -4.20852232]}
                rotation={[0, 0.42899644, 0]}
                scale={[-1, 1, 1]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_227.geometry}
                    material={materials.Texture}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_228.geometry}
                    material={materials.Screen}
                />
            </group>
            <group position={[4.68258953, 4.28984547, -1.55841529]} rotation={[0, -Math.PI / 3, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_230.geometry}
                    material={materials.Texture}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_231.geometry}
                    material={materials.Screen}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_4.geometry}
                material={materials.Texture}
                position={[0.16491139, 0.79438764, -1.97238803]}
                rotation={[-0.54409943, 0.92917339, -1.11946861]}
                scale={0.5}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_6.geometry}
                material={materials.Texture}
                position={[-2.79338956, 0.27000001, 1.81571054]}
                rotation={[-1.44023075, 1.21860407, 1.4317987]}
                scale={0.5}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_8.geometry}
                material={materials.Texture}
                position={[-5.60335827, 4.61523199, -0.02740134]}
                rotation={[-1.95532843, 0.16262987, 1.20244704]}
                scale={0.5}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_10.geometry}
                material={materials.Texture}
                position={[2.62069321, 1.98466921, -2.4728055]}
                rotation={[-0.41864707, -0.704254, -1.8512912]}
                scale={0.5}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_12.geometry}
                material={materials.Texture}
                position={[4.59783459, 3.45891547, 1.19009912]}
                rotation={[-1.23568014, -0.71873182, 0.47972881]}
                scale={0.5}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_14.geometry}
                material={materials['Material.001']}
                scale={13.00000095}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_16.geometry}
                material={materials.Texture}
                position={[0.62999964, 0, -3]}
                rotation={[0, 0.17035079, 0]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_18.geometry}
                material={materials.Texture}
                position={[-0.18604966, 0, -2.96229863]}
                rotation={[0, -0.06436888, 0]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_20.geometry}
                material={materials.Texture}
                position={[-2.3603785, 0.32000005, -2.01796389]}
                rotation={[-1e-7, 0.53432591, -Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_22.geometry}
                material={materials.Texture}
                position={[-2.28809643, 1.55999994, -2.26253891]}
                rotation={[0, -0.0116595, -Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_24.geometry}
                material={materials.Texture}
                position={[-2.42389226, 0.93773115, -2.24660468]}
                rotation={[Math.PI, -0.13567397, -Math.PI / 2]}
                scale={[-1.51999998, 1.51999986, 1.51999998]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_26.geometry}
                material={materials.Texture}
                position={[-2.19499373, 2.18773127, -1.86661148]}
                rotation={[Math.PI, -0.51193928, -Math.PI / 2]}
                scale={[-1.51999998, 1.51999998, 1.51999998]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_28.geometry}
                material={materials.Texture}
                position={[0.35298634, 2.35206962, -3.33635187]}
                rotation={[-0.25543825, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_30.geometry}
                material={materials.Texture}
                position={[0.18256298, 2.80053926, -2.85424685]}
                rotation={[0.09267864, 0.1458363, -0.01350592]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_32.geometry}
                material={materials.Texture}
                position={[-3.528301, 0, 0.58561635]}
                rotation={[Math.PI, -1.08510391, Math.PI]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_34.geometry}
                material={materials.Texture}
                position={[-2.89640379, 0.30000001, -1.46557319]}
                rotation={[Math.PI, -1.34690341, Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_36.geometry}
                material={materials.Texture}
                position={[-3.528301, 1.52767158, 0.58561635]}
                rotation={[0, 0.9105711, 0]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_38.geometry}
                material={materials.Texture}
                position={[1.89482749, 0, -1.94433057]}
                rotation={[0, -0.43633229, 0]}
                scale={[1.50000012, 1, 1.50000012]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_40.geometry}
                material={materials.Texture}
                position={[3.4231708, 0, 0.00461435]}
                rotation={[-Math.PI, 1.12680849, -Math.PI]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_42.geometry}
                material={materials.Texture}
                position={[3.22362876, 0, -0.80433249]}
                rotation={[0, -1.32441187, 0]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_44.geometry}
                material={materials.Texture}
                position={[3.53031349, 1.8342483, 0.44018674]}
                rotation={[-Math.PI, 1.32441182, Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_46.geometry}
                material={materials.Texture}
                position={[1.86230779, 1.61000001, -1.80666316]}
                rotation={[0, -Math.PI / 3, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_48.geometry}
                material={materials.Texture}
                position={[4.08590269, 2.18273115, 2.40985155]}
                rotation={[-0.00002083, -1.54790103, 1.5707755]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_50.geometry}
                material={materials.Texture}
                position={[4.2552557, 0.94273144, 2.21916485]}
                rotation={[-7.9e-7, -1.00191557, Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_52.geometry}
                material={materials.Texture}
                position={[4.31354475, 1.56500018, 2.34284496]}
                rotation={[Math.PI, 1.14924909, Math.PI / 2]}
                scale={[-1.51999998, 1.51999986, 1.51999998]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_54.geometry}
                material={materials.Texture}
                position={[3.86998606, 0.31500006, 2.34952354]}
                rotation={[3.14158212, 1.52551439, 1.57080686]}
                scale={[-1.51999998, 1.51999998, 1.51999998]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_56.geometry}
                material={materials.Texture}
                position={[3.95411205, 2.49099994, 1.60671997]}
                rotation={[0, -Math.PI / 3, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_58.geometry}
                material={materials.Texture}
                position={[-3.78992176, 0, 1.65607643]}
                rotation={[0, 1.39285199, 0]}
                scale={[-1.51999998, 1.51999998, 1.51999998]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_60.geometry}
                material={materials.Texture}
                position={[-3.78992176, 1.52767158, 1.65607643]}
                rotation={[-Math.PI, -1.21831904, -Math.PI]}
                scale={[-1.51999998, 1.51999998, 1.51999998]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_62.geometry}
                material={materials.Texture}
                position={[-3.69349265, 0, 2.58513498]}
                rotation={[0, -1.56769449, 0]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_64.geometry}
                material={materials.Texture}
                position={[-5.35951567, 2.18273115, 0.81081867]}
                rotation={[4.4e-7, 0.772299, Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_66.geometry}
                material={materials.Texture}
                position={[-5.61448002, 0.94273138, 0.81673276]}
                rotation={[0.00000197, 1.31828436, 1.57079427]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_68.geometry}
                material={materials.Texture}
                position={[-5.56364107, 1.56500018, 0.68980801]}
                rotation={[-Math.PI, -1.17095096, Math.PI / 2]}
                scale={[-1.51999998, 1.51999986, 1.51999998]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_70.geometry}
                material={materials.Texture}
                position={[-5.256598, 0.31500006, 1.0099864]}
                rotation={[-Math.PI, -0.7946857, Math.PI / 2]}
                scale={[-1.51999998, 1.51999998, 1.51999998]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_72.geometry}
                material={materials.Texture}
                position={[-5.47366953, 2.79447746, 0.74457061]}
                rotation={[Math.PI, -1.15538923, Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_74.geometry}
                material={materials.Texture}
                position={[-5.39013529, 4.03447723, 0.98553514]}
                rotation={[Math.PI, -0.60940323, Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_76.geometry}
                material={materials.Texture}
                position={[-5.28896999, 3.41220856, 0.89355695]}
                rotation={[-1.9e-7, 0.75673687, Math.PI / 2]}
                scale={[-1.51999998, 1.51999986, 1.51999998]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_78.geometry}
                material={materials.Texture}
                position={[-5.69624138, 4.66220856, 0.71771932]}
                rotation={[-4.7e-7, 1.13300212, Math.PI / 2]}
                scale={[-1.51999998, 1.51999998, 1.51999998]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_80.geometry}
                material={materials.Texture}
                position={[-5.28250837, 0, -2.32816601]}
                rotation={[0, 0.75469384, 0]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_82.geometry}
                material={materials.Texture}
                position={[-5.95203257, 0, -0.64145285]}
                rotation={[0, 0.95344689, 0]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_84.geometry}
                material={materials.Texture}
                position={[-5.48580503, 0, -1.38489509]}
                rotation={[-Math.PI, -0.98512965, -Math.PI]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_86.geometry}
                material={materials.Texture}
                position={[-4.47649574, 0, -2.74924016]}
                rotation={[-Math.PI, -0.56821379, -Math.PI]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_88.geometry}
                material={materials.Texture}
                position={[-3.01171827, 0, -3.78995609]}
                rotation={[0, 0.59746543, 0]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_90.geometry}
                material={materials.Texture}
                position={[-3.71566486, 0, -2.88565302]}
                rotation={[0, 0.64385748, 0]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_92.geometry}
                material={materials.Texture}
                position={[-2.08190393, 0, -4.32383013]}
                rotation={[-Math.PI, -0.59659777, -Math.PI]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_94.geometry}
                material={materials.Texture}
                position={[-1.01619136, 0, -4.48882437]}
                rotation={[0, 0.30837179, 0]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_96.geometry}
                material={materials.Texture}
                position={[-0.08397174, 0, -5.02558804]}
                rotation={[-Math.PI, -0.03916773, -Math.PI]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_98.geometry}
                material={materials.Texture}
                position={[-5.31454515, 1.83273113, -1.41169095]}
                rotation={[8.9e-7, 1.06203687, Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_100.geometry}
                material={materials.Texture}
                position={[-4.18072653, 1.83273113, -3.06424904]}
                rotation={[-Math.PI, -0.46454065, -Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_102.geometry}
                material={materials.Texture}
                position={[-1.75833631, 1.83273113, -3.60475731]}
                rotation={[-0.00000112, -1.16495686, Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_104.geometry}
                material={materials.Texture}
                position={[-0.25441337, 1.83273113, -5.54224062]}
                rotation={[0.00002695, 1.55310568, 1.57076937]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_106.geometry}
                material={materials.Texture}
                position={[-4.19391251, 1.83578789, -2.76768398]}
                rotation={[-1.4e-7, 0.65542488, Math.PI / 2]}
                scale={[-1.51999998, 1.51999998, 1.51999998]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_108.geometry}
                material={materials.Texture}
                position={[-5.28250837, 2.14323854, -2.32816601]}
                rotation={[-Math.PI, -0.75469404, -Math.PI]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_110.geometry}
                material={materials.Texture}
                position={[-5.95203257, 2.14323854, -0.64145285]}
                rotation={[-Math.PI, -0.95344721, -Math.PI]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_112.geometry}
                material={materials.Texture}
                position={[-5.48580503, 2.14323854, -1.38489509]}
                rotation={[0, 0.98512997, 0]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_114.geometry}
                material={materials.Texture}
                position={[-4.47649574, 2.14323854, -2.74924016]}
                rotation={[0, 0.56821411, 0]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_116.geometry}
                material={materials.Texture}
                position={[-3.01171827, 2.14323854, -3.78995609]}
                rotation={[-Math.PI, -0.5974656, -Math.PI]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_118.geometry}
                material={materials.Texture}
                position={[-3.7269249, 2.14323854, -3.09959292]}
                rotation={[-Math.PI, -0.64385778, -Math.PI]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_120.geometry}
                material={materials.Texture}
                position={[-2.08190393, 2.14323854, -4.32383013]}
                rotation={[0, 0.59659786, 0]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_122.geometry}
                material={materials.Texture}
                position={[-1.01619136, 2.14323854, -4.48882437]}
                rotation={[-Math.PI, -0.30837211, -Math.PI]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_124.geometry}
                material={materials.Texture}
                position={[-0.08397174, 2.14323854, -5.02558804]}
                rotation={[0, 0.03916806, 0]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_126.geometry}
                material={materials.Texture}
                position={[-5.31454515, 3.97596955, -1.41169095]}
                rotation={[8.9e-7, 1.06203687, Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_128.geometry}
                material={materials.Texture}
                position={[-4.18072653, 3.97596955, -3.06424904]}
                rotation={[-Math.PI, -0.46454065, -Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_130.geometry}
                material={materials.Texture}
                position={[-1.17281663, 3.97596955, -4.4492569]}
                rotation={[8e-8, 0.16843083, Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_132.geometry}
                material={materials.Texture}
                position={[-0.94127303, 3.97596955, -4.66396093]}
                rotation={[Math.PI, 0.01769057, -Math.PI / 2]}
                scale={1.51999998}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_134.geometry}
                material={materials.Texture}
                position={[-4.19391251, 3.97902656, -2.76768398]}
                rotation={[-1.4e-7, 0.65542488, Math.PI / 2]}
                scale={[-1.51999998, 1.51999998, 1.51999998]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_136.geometry}
                material={materials.Texture}
                position={[-1.09500229, 4.29068279, -4.43409157]}
                rotation={[0, 0.35669769, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_138.geometry}
                material={materials.Texture}
                position={[-5.24585009, 4.29068279, -1.4662149]}
                rotation={[0, 1.24565589, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_140.geometry}
                material={materials.Texture}
                position={[5.53140306, 2.18273115, 0.17374715]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_142.geometry}
                material={materials.Texture}
                position={[5.78636789, 0.94273138, 0.17966112]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_144.geometry}
                material={materials.Texture}
                position={[5.73552942, 1.56500018, 0.05273661]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_146.geometry}
                material={materials.Texture}
                position={[5.42848635, 0.31500006, 0.37291488]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_148.geometry}
                material={materials.Texture}
                position={[5.64555788, 2.79447746, 0.10749897]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_150.geometry}
                material={materials.Texture}
                position={[5.56202364, 4.03447723, 0.34846362]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_152.geometry}
                material={materials.Texture}
                position={[5.46085787, 3.41220856, 0.25648531]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_154.geometry}
                material={materials.Texture}
                position={[5.86812925, 4.66220856, 0.0806478]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_156.geometry}
                material={materials.Texture}
                position={[4.85593462, 0, -2.54052329]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_158.geometry}
                material={materials.Texture}
                position={[5.52545977, 0, -0.85380995]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_160.geometry}
                material={materials.Texture}
                position={[5.05923128, 0, -1.59725225]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_162.geometry}
                material={materials.Texture}
                position={[4.04992247, 0, -2.96159744]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_164.geometry}
                material={materials.Texture}
                position={[2.58514452, 0, -4.00231314]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_166.geometry}
                material={materials.Texture}
                position={[3.28909159, 0, -3.0980103]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_168.geometry}
                material={materials.Texture}
                position={[1.65533113, 0, -4.53618717]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_170.geometry}
                material={materials.Texture}
                position={[0.58961821, 0, -4.70118141]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_172.geometry}
                material={materials.Texture}
                position={[4.88797235, 1.83273113, -1.62404811]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_174.geometry}
                material={materials.Texture}
                position={[3.75415277, 1.83273113, -3.27660632]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_176.geometry}
                material={materials.Texture}
                position={[1.33176279, 1.83273113, -3.81711459]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_178.geometry}
                material={materials.Texture}
                position={[3.76733923, 1.83578789, -2.98004127]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_180.geometry}
                material={materials.Texture}
                position={[4.85593462, 2.14323854, -2.54052329]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_182.geometry}
                material={materials.Texture}
                position={[5.52545977, 2.14323854, -0.85380995]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_184.geometry}
                material={materials.Texture}
                position={[5.05923128, 2.14323854, -1.59725225]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_186.geometry}
                material={materials.Texture}
                position={[4.04992247, 2.14323854, -2.96159744]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_188.geometry}
                material={materials.Texture}
                position={[2.58514452, 2.14323854, -4.00231314]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_190.geometry}
                material={materials.Texture}
                position={[3.30035162, 2.14323854, -3.31195021]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_192.geometry}
                material={materials.Texture}
                position={[1.65533113, 2.14323854, -4.53618717]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_194.geometry}
                material={materials.Texture}
                position={[0.58961821, 2.14323854, -4.70118141]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_196.geometry}
                material={materials.Texture}
                position={[4.88797235, 3.97596955, -1.62404811]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_198.geometry}
                material={materials.Texture}
                position={[3.75415277, 3.97596955, -3.27660632]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_200.geometry}
                material={materials.Texture}
                position={[0.746243, 3.97596955, -4.66161394]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_202.geometry}
                material={materials.Texture}
                position={[3.76733923, 3.97902656, -2.98004127]}
                scale={[-1, 1, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_204.geometry}
                material={materials.Texture}
                position={[3.19776678, 4.29068279, -3.0920527]}
                rotation={[0, -0.56294714, 0]}
                scale={[-1, 1, 1]}
            />
        </group>
    )
}

useGLTF.preload('/models/old_computers.glb')

export default OldComputers;
